name: Deploy to ECS
on: 
  workflow_dispatch:
  
jobs:
  setenv:
    name: test
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    timeout-minutes: 25
    steps:
        - uses: actions/checkout@v4

        - run: sudo apt update && sudo apt install yq

        - run: yq -p yaml -o json input.yml

        - run: echo "buildApi=true" >> $GITHUB_ENV

        - run: echo ${{ env.buildApi }}
