name: env tests
on: 
  workflow_dispatch:
  
jobs:
  setenv:
    name: test
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    timeout-minutes: 25
    steps:
        - uses: actions/checkout@v4

        - run: sudo snap install yq --channel=v3/stable

        - run: yq -p yaml -o json input.yml

        - run: echo "buildApi=true" >> $GITHUB_ENV

        - run: echo ${{ env.buildApi }}
  retrieveEnv:
    name: retrieving
    needs: [setenv]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.buildApi }}
